### ISSUE TITLE
FEAT: Refresh page after update check

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#100]
Issue:  Refresh page after update check

**Comment by wjbeckett** [comment]
Let's just refresh the update check module instead of a whole page refresh. 

You know I hated whole page refreshes. 😜

Simple enough to do with jquery/Ajax, etc.

**Comment by wjbeckett** [comment]
Let's just refresh the update check module instead of a whole page refresh. 

You know I hate whole page refreshes. 😜

Simple enough to do with jquery/Ajax, etc.

**Comment by seanvree** [comment]
@wjbeckett  agreed brother.

**Comment by jonfinley** [comment]
this is complete right?

**Comment by seanvree** [comment]
@jonfinley  no.  It's a small thing.  Wanted to refresh the UI after you do an update check so it doesn't sit there and say "you already have the latest version".

**Comment by seanvree** [comment]
Added to test-bootstrap branch


![image](https://user-images.githubusercontent.com/8906637/36064041-0360e6b0-0e3a-11e8-9e4e-b76d01821f92.png)

**Comment by seanvree** [comment]
Added with version 0.14.0
