### ISSUE TITLE
FEAT: Add ms response time

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#113]
Feature:  Add ms response time for individual services

**Comment by jonfinley** [comment]
can we do this as a mouse over?

**Comment by seanvree** [comment]
@jonfinley  I don't see why not.

**Comment by seanvree** [comment]
Almost done. Projected rollout NLT 01 JUN 18:

![monitorr_update_22may18](https://user-images.githubusercontent.com/8906637/40391231-6f7592d8-5dcc-11e8-9c29-d2137b036c4e.gif)

**Comment by seanvree** [comment]
ADDED: with v 1.7.6 https://github.com/Monitorr/Monitorr/releases
