### ISSUE TITLE
Wrong docker image name in wiki

### ISSUE THREAD

**Issue by romanar** [Monitorr/Monitorr#128]
Wrong docker image name `monitorr/docker-monitorr` instead of `monitorr/monitorr` under `Usage:`
```
docker create \
--name=monitorr \
--restart=on-failure \
-v <host path for config:/config \
-v :/var/log \
-e TZ= \
-p 80:80 \
monitorr/docker-monitorr
```
in `02 Config: Docker` section.

**Comment by seanvree** [comment]
@romanar  Thanks man.  We are about to push 1.0 so this will change.
