### ISSUE TITLE
Bug: Updating Docker container will wipe user images

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#138]
**Issue**:  When updating the Docker container, any custom images placed in the /assets/img directory to use for "service image" in Monitorr settings will be removed when docker image is updated. 

**Resolution**: symlink user images
```
ln -s /app/images /config/www/monitorr/assets/data/usrimg
```

**Status**:  Fix in development

**Comment by seanvree** [comment]
pushed to develop

**Comment by jonfinley** [comment]
Working for me.

**Comment by seanvree** [comment]
fixed with https://github.com/Monitorr/Monitorr/commit/1a3214709402b602f28d3bb7745489df060b1845
