### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Kazz3r24** [Monitorr/Monitorr#139]
## Your environment:

- **Operating system**: Ubuntu 16.04

- **Webserver**:    Apache 2  2.4.18-2ubuntu3.5

- **PHP Version**:      PHP7.0  7.0.28-0ubuntu0.16.04.1

- **Monitorr Version**:   1.5.0m  

## Describe your issue:

I have read the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/05-Troubleshooting

My apache automatically redirects connections to https using a LetsEncrypt SSL certificate (it's not the browser because Chrome and Firefox have the same behavior and I clear my cache on each attempt). Currently I have successfully registered and created the data directory and created a user. When I try to log in I get stuck in a loop, after entering my credentials and hitting return to log in I'm left with a blank screen with the exception of the pane on the left. If I click on any links on the left I'm brought back to the log in page so I cannot effectively configure the rest of Monitorr. Is there a log location so I can see where the issue is? Has anyone else run into this issue? Or is the issue with my SSL?

Any help is appreciated!
P.s. I haven't made it far enough in the configuration to know this yet, but is it possible to install this on a server that monitors a remote server? Most of my web servers on various servers I have are configured with https, so if this is possible I can create another droplet and NOT configure https on it to see if that works.

**Comment by seanvree** [comment]
@Kazz3r24 I'm not familiar with the term "droplet", care to learn me?

A couple follow up questions - 

To your update, are you saying you can't access the settings page via SSL, or one of the services your monitoring is SSL, and reporting OFFLINE?

If it's the first - a couple follow up questions: 
1 - So when you try to connect via SSL, you CAN get to the settings log-in page, but can't log in, right?  When you get that blank screen and the exception in the left pane, can you maybe post a screenshot?

2 - Are you browsing to the monitorr settings page on the server where monitorr is hosted (ie "localhost", or are you browsing via remote machine on the LAN or WAN?

If it's a specific service that you're monitoring via SSL, but reporting as down:

- Monitorr isn't coded to require SSL either when on the settings page or the remote services it monitors, so like you stated, I'm assuming there is a confliction with apache?

- As far as installing on a server that monitors a "remote server" - Yes, that's exactly what it's designed to do.  In the services configuration, you would simply put in the IP address or hostname of the remote server with the port, so  http://remoteserverIP:80 .  This works with SSL as well (https://remoteserverIP:443)

Let me know!

THX

**Comment by Kazz3r24** [comment]
A droplet is just a cloud-based web server, you can get them dirt cheap ($0.07/hr based on usage) within seconds from DigitalOcean.
To clarify, I am able to get to the settings page and create the data directory as well as create the user (I assume) but as soon as I select "create" for the user, I'm left with a blank portion in the middle of the screen, left pane still visible. Nothing is reporting incorrectly, I just physically cannot proceed which I believe is due to the webserver running on SSL. The image below is literally just after I click "create" for the initial user, so I am unable to proceed beyond this point and configure any services etc. (technically this answers #1)
2 - Because I am on a droplet I only have ssh access, so no localhost sadly.
Monitorr works flawlessly as long as it's on a web server running http.

Please let me know if there's any further information I may provide.

![image](https://user-images.githubusercontent.com/15070472/38911163-681cdaa6-429b-11e8-95c6-c276785d2213.png)

**Comment by Kazz3r24** [comment]
When I click any link on the left it brings me to the log in form, after entering the correct credentials, I'm again left with the above screen.

**Comment by Kazz3r24** [comment]
Sorry, thinking on the fly here. The main reason I asked about remote monitoring is I noticed the system usage is only reporting for localhost, if this can be changed to monitor system resources of a remote server, problem solved!

**Comment by Kazz3r24** [comment]
It likely is a configuration issue with Apache; however, I've attempted the install on several webservers, some running SSL and I run into the same issue. Only success I had was a webserver running without SSL.

**Comment by jonfinley** [comment]
I personally do not use Apache, but run using nginx and have not encountered some of these issues.

With that said, are their any error in the console of your browser and/or your apache logs? I might be able to narrow down. 

and not to ask the dumb question, but I am assuming you chowned to your apache user.

Thanks!

**Comment by Kazz3r24** [comment]
I will absolutely take you up on that (not now obviously), but I do want to get away from Apache. My main thing is a wordpress install, do you know if I'm able to simply move my wordpress install out of /var/www/html, remove apache, install nginx then put it back? I'm looking for the least hairpulling method ahaha.
I clear the browser cache after every attempt just in case, as far as I'm aware I'm not blocking iframes using apache, but I will look into that now that you mention it!

**Comment by Kazz3r24** [comment]
Just an update, I checked over the error logs for apache and found this.

[Wed Apr 18 00:53:31.135152 2018] [:error] [pid 20019] [client x.x.x.x:xxxx] FastCGI: server "/usr/lib/cgi-bin/php7-fcgi" stderr: PHP message: PHP Notice:  Use of undefined constant CURLOPT_TCP_FASTOPEN - assumed 'CURLOPT_TCP_FASTOPEN' in /var/www/html/Monitorr/assets/php/check.php on line 60, referer: https://notmydomainname.com/Monitorr/

[Wed Apr 18 00:55:31.160109 2018] [:error] [pid 20019] [client x.x.x.x:xxxxx] FastCGI: server "/usr/lib/cgi-bin/php7-fcgi" stderr: PHP message: PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in /var/www/html/Monitorr/assets/php/check.php on line 60, referer: https://notmydomainname.com/Monitorr/

I'm doing some research now to see if I can dig into it more.

Eventually I may find the ambition to move everything over to Nginx, it seems like it'll be tedious but trivial (crosses fingers)

**Comment by Kazz3r24** [comment]
Alright, I bit the proverbial bullet and got rid of apache, I had a backup site running anyway so I've now got nginx installed, calling it a night and I'll pick it up tomorrow :)

**Comment by seanvree** [comment]
@Kazz3r24 I'm looking into this now. I'll have some answers tomorrow.  Quick question, does the main site open OK?  /index.php  ?

**Comment by Kazz3r24** [comment]
Ahaha it does now yes. I wouldn't worry too much about the Apache issue, no going back now :P. I've got nginx running and just cloned monitorr, it now opens fine, registered fine, everything is fine. Tomorrow I'll tackle SSL and getting the ball rolling. Thank you guys very much for your efforts and this ungodly hour (0210am here). If I run into more issues I'll let you guys know. I'll leave the case open for now if you like, or I can close it. I'd consider myself all good now though. I am curious to see your results though :) likely it's just a ME problem ahaha.

**Comment by Kazz3r24** [comment]
Another update for you guys, it was definitely something wrong with my Apache install (no idea what though). I've just finished setting up SSL on my nginx install for Monitorr and it works flawlessly. Very glad I made the switch. Very weird issue!

**Comment by seanvree** [comment]
@Kazz3r24  yeah, let us know if you have any more issues moving to NGINX.  

As far as the " stderr: PHP message: PHP Warning: curl_setopt() expects parameter 2 to be integer, string given in /var/www/html/Monitorr/assets/php/check.php on line 60, referer: " error, it's just a warning, it's irrelevant.

**Comment by Kazz3r24** [comment]
@jonfinley I don't see any option on GitHub to be able to send a message directly to you, so I apologize to all for commenting here as it's off-topic. I'd like to ask you a couple of questions regarding reverse proxy and nginx. I have set one up successfully before, but the system I'm working on now is giving me issues. If there is somewhere I should ask this rather than in here please let me know.

**Comment by seanvree** [comment]
@Kazz3r24  https://discord.gg/YKbRXtt
