### ISSUE TITLE
FEAT: Github Update

### ISSUE THREAD

**Issue by rob1998** [Monitorr/Monitorr#151]
Issue: The update link sends users to Github, while it would be much nicer to just pull the new version from Github when the link is clicked

Resolution: Implement function which enables user to pull the latest Github release

**Comment by seanvree** [comment]
@rob1998  what "update link" are you talking about here?  

The "check for update" button on the info page triggers the actual update. 

![image](https://user-images.githubusercontent.com/8906637/39278631-1aa8f4c6-48a9-11e8-9e2f-c18263f3cb41.png)

**Comment by seanvree** [comment]
@rob1998  ahhh, I see what you're saying.  I guess the thought is that someone might want to see "what's new" before going thru the process of logging in and updating...but Yeah, I see what you're saying.

**Comment by seanvree** [comment]
@rob1998  I'm going to close this and reference https://github.com/Monitorr/Monitorr/issues/123  as I think that's what we'll link it to.
