### ISSUE TITLE
Organizr Integration - All EXCEPT Clock

### ISSUE THREAD

**Issue by zhdenny** [Monitorr/Monitorr#164]
Integration to Oganizr works great! But I want to view everything EXCEPT the Time/Clock. You do not have Custom HTML posted for this. How would I do this?

**Comment by seanvree** [comment]
@zhdenny  are you talking only on the index.min site?

If you want the clock to NOT show ONLY on the index.min site you would use the following CSS in the User Preferences Custom CSS editor:


```
#time {
    visibility: hidden !important;
}
```


![image](https://user-images.githubusercontent.com/8906637/40863190-c4dd7ed2-65a3-11e8-8014-74e0267009fe.png)


However if you want the hide the clock on the main site you would use:

```
#clock {
    visibility: hidden !important;
}
```


![image](https://user-images.githubusercontent.com/8906637/40863314-2ffd12cc-65a4-11e8-8da3-833ef6a6cf61.png)

**Comment by ansuz07** [comment]
To piggyback on this, how would one go about removing the drop shadow on the box that surrounds the stats on the index.min page?  I can find everything but that in the main css file.

Thanks!

**Comment by rob1998** [comment]
Would it be possible you're talking about the box-shadow? I think Corry asked it before on Discord, don't know if he figured it out.

**Comment by ansuz07** [comment]
Yeah - the box-shadow. I is the one element I can't figure out to how remove/customize:

![image 1](https://user-images.githubusercontent.com/29070297/45317336-55909900-b4ff-11e8-9f76-ae41ecd3d3b7.jpg)

**Comment by rob1998** [comment]
Try something like:
```#center {
    box-shadow:none;
}```

And maybe: 
```
#stats {
    box-shadow:none;
}
```

**Comment by ansuz07** [comment]
The "center" attribute was it - using none took care of it.  Thanks!
