### ISSUE TITLE
This error shows up whenever something is offline

### ISSUE THREAD

**Issue by kevinb77** [Monitorr/Monitorr#172]
## Your environment:

- **Operating system**: Windows 10P x65 build: 1709

- **Webserver**:       NGINX v. 3.8

- **PHP Version**:      7.2.1 x64 NTS

- **Monitorr Version**:   0.21m  (in the footer of the Monitorr UI)

## Describe your issue:

I have read the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/06-Troubleshooting

Warning: fsockopen(): unable to connect to thepiratebay.org::5 (The requested address is not valid in its context. ) in C:\nginx\html\Monitorr\assets\php\check.php on line 126

The TPB just happens to be down this morning. I double checked the original script against my script and they both match up. Not sure where to go from here.

**Comment by seanvree** [comment]
@kevinb77  what port are you using?  Can you post a screenshot of the service from the "services configuration" page?

**Comment by kevinb77** [comment]
http://localhost:80

[image: TPB offline.JPG][image: TPB Service.JPG]

**Comment by seanvree** [comment]
@kevinb77  I'm confused, you're using localhost:80 as the "check URL" but it's saying "thepiratebay.org::5" ??

**Comment by seanvree** [comment]
Can you post a screenshot like this:


![image](https://user-images.githubusercontent.com/8906637/41700368-db9217bc-74dc-11e8-8914-88c1a2134801.png)

**Comment by kevinb77** [comment]
![new service](https://user-images.githubusercontent.com/5552571/41717844-0bde75b8-7529-11e8-84ba-8e204cf0becf.JPG)

Here you go

**Comment by seanvree** [comment]
So are you saying this service shows offline?  Is the port open? Can you access that same check URL from a browser on the server?

**Comment by kevinb77** [comment]
Yes, this services shows off line and it is offline, which is fine. I just
do not understand why this error is showing on the status page [image: TPB
offline.JPG]

**Comment by seanvree** [comment]
@kevinb77  can you post a screenshot?  I'm not sure what error you're talking about?

**Comment by rob1998** [comment]
@kevinb77 I'm guessing you also have a service for thepiratebay configured? Can you maybe screenshot the settings for that service? Also, please make a screenshot of your index page (the page that displays the state of your services)

**Comment by seanvree** [comment]
This is operator error. I'm closing this.

**Comment by seanvree** [comment]
@kevinb77  I just figured it out. 

In your PHP.ini file, you have "display_errors = on". This should only be used for developmental purposes.  Set this value to OFF

```
display_errors = Off
```

**Comment by kevinb77** [comment]
Where is this file located?

**Comment by seanvree** [comment]
@kevinb77  go to the Monitorr settings page -> INFO -> and on the PHPinfo frame, you'll see "Loaded Configuration File"



![image](https://user-images.githubusercontent.com/8906637/41777901-c84dd776-75e1-11e8-8f00-088205c5941b.png)

**Comment by kevinb77** [comment]
Got it! Thanks for your assistance!
