### ISSUE TITLE
FEAT/ BUG:  Disable browser output error if service is down

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#174]
Issue:  If the user has display_errors: ON in php.ini file, how do we prevent the UI from displaying that an error is down.   Is this even a good idea?

REf:  https://github.com/Monitorr/Monitorr/issues/172#issuecomment-399215477

**Comment by rob1998** [comment]
I'll look into it

**Comment by seanvree** [comment]
Fixed with v 1.7.6 https://github.com/Monitorr/Monitorr/releases
