### ISSUE TITLE
Unable to view /index.min.php in organizr v1/v2 homepage on iOS

### ISSUE THREAD

**Issue by gilbN** [Monitorr/Monitorr#182]
## Your environment:

- **Operating system**: Unraid / Docker

- **Monitorr Version**:  develop

## Describe your issue:
Unable to view /index.min.php in organizrv1/v2 on iOS

/monitorr works but adding /monitorr/index.min.php shows blank space.

**Comment by seanvree** [comment]
@jonfinley  Can you look at this when you get back?  I can't test this as I don't have an iOS device. It works in the chrome iPhone emulator, so I don't get it?

**Comment by gilbN** [comment]
I'm guessing it works in chrome iPhone emulator as that doesn't use webkit.

**Comment by seanvree** [comment]
Is this still an issue @gilbN  ?

**Comment by seanvree** [comment]
Investigating:

```
<div id="announcementRow" class="row"><h4 class="pull-left"><span>Monitorr</span></h4><hr class="hidden-xs"></div>
<div style="overflow:hidden; height:260px">
<iframe class="iframe" frameborder="0" src="https://monitorr.domain.com/index.min.php"></iframe>
</div>
```
