### ISSUE TITLE
TZ is not working correctly

### ISSUE THREAD

**Issue by wikkixwikki** [Monitorr/Monitorr#191]
## Your environment:

- **Operating system**: Ubuntu 16.04 server

- **Webserver**:       NGINX v. 1.10.3

- **PHP Version**:      7.0-cli

- **Monitorr Version**:   1.7.6m
## Describe your issue:

I have used both of the following when setting up the docker container and neither seem to work. 
-v /etc/localtime:/etc/localtime:ro \  
-e TZ=America/Denver \

I continue to get GMT as the TZ rather than MST or even MT.

**Comment by rob1998** [comment]
Did you also set a timezone on your Monitorr settings page?

**Comment by jonfinley** [comment]
The /etc/localtime:/etc/localtime:ro should auto pull the timezone to the container. I believe that is where the error lies, As we have gotten linux to auto populate the time. Otherwise yes, it does default to the GMT.

**Comment by seanvree** [comment]
@wikkixwikki with the latest version of Monitorr you MUST set the TZ manually.
