### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gabriellluz** [Monitorr/Monitorr#192]
## Your environment:

- **Operating system**: Windows 10P x65 build: 1709

- **Webserver**:       NGINX v. 3.8

- **PHP Version**:      7.2.1 x64 NTS

- **Monitorr Version**:   0.21m  (in the footer of the Monitorr UI)

## Describe your issue:

I have read the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/06-Troubleshooting

Hi. I have a problem. I can ping an external address using a CMD (Windows' Terminal) and it's ok. But Monitorr can't ping the same website. It says it's offline.

**Comment by rob1998** [comment]
Did you try changing the check type to Ping Only?

**Comment by seanvree** [comment]
@gabriellluz are you still having this issue?
