### ISSUE TITLE
Organizr integration of multiple hdd status

### ISSUE THREAD

**Issue by Hakker** [Monitorr/Monitorr#194]
Small request for down the line to make it possible to show multiple hdd status badges when you use the organizr integration html code.

**Comment by seanvree** [comment]
@Hakker  I'll look into this.  TBH, that's what the main index.php is for.  The whole point of the index.min.php is for just that - to be minimal.  So, I'll take a look, but don't get your hopes up.  The

**Comment by Faerus** [comment]
One HD is never more important than another so this is min mandatory information and should be displayed. I'm looking forward this too, or you could add option to toggle what we want to see on min version.
I would rather got all my hdd than the horloge for example.

@seanvree why has the request been closed, is it available on some branch ?
