### ISSUE TITLE
No Options / Only Text on Monitorr Registration Page

### ISSUE THREAD

**Issue by BzowK** [Monitorr/Monitorr#196]
## Your environment:
- **Operating system**: Windows 10 x64
- **Webserver**: NGINX 1.15.2
- **PHP Version**: 7.2.8
- **Monitorr Version**: 1.7.7d

## Describe your issue:
Hey Guys - 

_To start, yes - I have read and followed the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/06-Troubleshooting without luck.  :)_

I'm having an issue on a new install of Monitorr where I am able to browse to it's home page (.../monitorr/index.php) and able to go to Monitorr Settings as I am initially prompted to do.  Once I click the link for Monitorr Registration, I get a page with steps only in text - no options.  [Here's a screenshot.](https://kelnetcloud.com/owncloud/index.php/apps/files_sharing/ajax/publicpreview.php?x=1441&y=393&a=true&file=monitorr1.png&t=UYG2Q3KT9yVgBlt&scalingup=0)

If I browse there manually (.../monitorr/assets/config/_installation/_register.php), I am only presented with text [as shown here](https://kelnetcloud.com/owncloud/index.php/apps/files_sharing/ajax/publicpreview.php?x=1441&y=393&a=true&file=monitorr2.png&t=MFktbwRAQtYo1zW&scalingup=0).

I thought this may be a PHP issue, but looking at phpinfo, [all looks fine as all components are green](https://kelnetcloud.com/owncloud/index.php/apps/files_sharing/ajax/publicpreview.php?x=1441&y=393&a=true&file=monitorr3.png&t=d0eiLSEM41HLu9L&scalingup=0).  

The only things I've thought may be the issue are that I am 
- accessing it via HTTPS.  Don't currently listen on 80, but could try if that was the issue.
- PHP Config file in use seems to be the one in my old Apache folder as per the phpinfo.php page.  Wouldn't think that would make too much of a difference.

To note, I ran into this exact issue when testing it a couple of months ago when I tried the master version at that time as well.  Today's test was a brand new download / install.  I do have a new folder waiting to be the data folder in the root of C:\, but haven't been able to enter it yet.

Suggestions?  Thanks

**Comment by seanvree** [comment]
@BzowK  are you still having this issue?

**Comment by seanvree** [comment]
No response. Closed.
