### ISSUE TITLE
Cannot Access Monitorr via NGINX Reverse Proxy

### ISSUE THREAD

**Issue by BzowK** [Monitorr/Monitorr#197]
## Environment Details
- **Monitorr**
	- **Operating system**: Docker Atomic (Fedora 28)
	- **Monitorr Version**: 1.7.7d
	- **PHP Version**: 7.1.17
	- **Docker Host IP**: 192.168.0.21
	- **Mapped Host Port**: 7979 *(Forwarded 80 from the container)*
- **NGINX**
	- **Operating system**: Windows 10 x64 1809
	- **Webserver**: NGINX v. 1.14.2
	- **PHP Version**: 7.28 VC15 x64 Non Thread Safe 
	- **Hosts**: Reverse Proxy adding SSL Layer

*Initial testing was done using the main 1.7.6m build, but upgraded to the 1.7.7d develop version and got the exact same results.*

## My Goal
To be able to access Monitorr by browsing to https://mydomain.com/monitorr

## The Issue
When browsing to Monitorr via Reverse Proxy (https://mydomain.com/monitorr) using a standard RP configuration, it displays the correct title, but "Monitorr is loading..." never goes away.  Browsing directly to Monitorr's IP:port from the system hosting NGINX displays everything correctly.  I need to find out how to add base path to Monitorr's URL *(if possible)* or find a working RP config for NGINX which does not require a matching base path in source URL.

## Details + What I've Tried
*Below are more details as well as examples of configuration's I'm currently testing* 

Hey Guys - 

I decided to try out Monitorr via Docker instead of on my Windows system so successfully installed and configured the container this morning - it works great!  The only configuration pending is to add it to my reverse proxy configuration which is hosted by NGINX which is currently installed on Windows.  I already use this NGINX installation for reverse proxy with over 15 other apps hosted on the local Windows system, docker containers, and others.  Following the format as the others, I want to be able to access Monitorr by visiting https://mydomain.com/monitorr.  

_To note, SSL is applied at the reverse proxy layer by NGINX.  The source URLs I use for other apps I run through RP are HTTP as well._ 

Unfortunately, I can't figure out how to add a custom base path to Monitorr's URL.  I looked through Monitorr's settings which is where it usually is for similar apps as well as through some of its config files. It is usually required to use the config template I typically use which is shown below:

		location /monitorr {
			proxy_pass        http://192.168.0.21:7979/monitorr/;
			proxy_set_header  X-Real-IP  $remote_addr;
			proxy_set_header        Host            $host;
			proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header        X-Forwarded-Proto $scheme;
			proxy_redirect off;
			proxy_buffering off;
		}

I went ahead and tried it anyways by leaving off the base path therefore making the 2nd string above 

			proxy_pass        http://192.168.0.21:7979/;

_To note, am am able to successfully browse to and use Monitorr from the system NGINX is hosted upon at "http://192.168.0.21:7979".  For the heck of it, I tried browsing to "http://192.168.0.21:7979/monitorr", but not surprisingly got a 404_

As expected, it did not work.  When browsing to https://mydomain.com/monitorr after applying the above config, it looks like it will work as the header appears with custom title and the clock shows my configured timezone, but the "Monitorr is loading..." box never goes away.  Also, two small yellow exclamation marks are shown in the upper left and the resource usage box in the upper right is also empty.  Clicking the "Monitorr Settings" link at the bottom opens a new blank page which states "No input file specified."  NGINX's error.log shows nothing.
 
Next, I tried a 2nd config which is what I use for Deluge's WebUI over RP as it also doesn't have a base path in its URL. I made a copy of it, substituted Monitorr's address in place of Deluges, then restarted the NGINX service. Regardless, I got the exact same result as with the first config.

*If it makes a difference, Deluge is hosted on the same system as NGINX which is 192.168.0.25.*

		location /monitorr/ {
			allow 127.0.0.1;
			allow 192.168.0.0/24;
			deny  all;
			proxy_pass	http://192.168.0.21:7979/;
			proxy_redirectoff;
			proxy_set_header  Host$host;
			proxy_set_header  X-Real-IP   $remote_addr;
			proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header  X-Monitorr-Base   "/monitorr/";
			proxy_pass_header Set-Cookie;
			proxy_pass_header P3P;
		}

Lastly, I tried a 3rd config which similar to Deluge, I use for Portainer's webui with no base path.  I had high hopes for this one as the only difference between Portainer's address and Monitorr's is the port as both are containers on the same Docker host.  Unfortunately, it also yeilded the same results.  Below is what I tested:

		location /monitorr/ {
			proxy_http_version 1.1;
			proxy_set_header Connection "";
			proxy_pass http://192.168.0.21:7979/;
		}
		location /monitorr/api/websocket/ {
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_http_version 1.1;
			proxy_pass http://192.168.0.21:7979/api/websocket/;
		}

*I probably didn't need the 2nd half of the above config as Monitorr doesn't seem to have a similar path, but did check to see if other paths needed to be added yet couldn't find any.*

##Container Configuration
In case its needed *(rather provide too much info than not enough if you can't tell)* :), below is the string I used to install the Monitorr container in Docker.  I only added ":develop" recently when I decided to see if I got different results with it's version

    docker run -d \
       --name=Monitorr \
       --restart=always \
       -v ~/monitorr/app:/app:z \
       -v ~/monitorr/datadir:/datadir:z \
       -e TZ=America/Chicago \
       -e PGID=1001\
       -e PUID=1001 \
       -p 7979:80 \
       monitorr/monitorr:develop

##Overall
Overall, I really need one of two things:

- Find out how to add a base path in Monitorr's configuration so that I can successfully access it via http://192.168.0.21:7979/monitorr
- A reverse proxy config snippet which will allow me to access Monitorr via https://mydomain.com/monitorr and have the same configuration / settings appear as when visiting it directly via IP 

Any suggestions are welcome and I'm happy to provide additional information if needed.  

Thank You!

**Comment by BzowK** [comment]
Guys - 

I ended up joining the Discord channel and finding the solutions causing **Monitorr Stuck on "Monitorr is loading..."**.  I've listed them below for reference if anyone else experiences the same.

**Issue #1**
It turns out that a default Docker Monitorr container installation can be accessed with or without "/monitorr/" after the IP:port.  The key I was missing was that I was missing the trailing "/" when testing directly as well as within the reverse proxy config.  Therefore, below is the config I successfully used with NGINX for RP with it:

> 		location /monitorr {
> 			proxy_pass http://192.168.0.21:7979/monitorr/;
> 			add_header X-Frame-Options SAMEORIGIN;
> 			proxy_set_header Host $host;
> 			proxy_set_header X-Real-IP $remote_addr;
> 			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 		}

Issue #2 
Even though I could now access directly using "/monitorr/", I still got Monitorr Stuck on "Monitorr is loading..." when visiting via RP (not directly).  It turned out, the PHP I used for NGINX was "hijacking" the PHP which Monitorr used within the container.  To resolve this, configured my nginx.conf file so that it's PHP would only apply to the root of the web server which is why it was there in the first place.

Therefore, I replaced the below two separated configs:

>             location / {
>             root   html;
>             index index.php index.html index.htm;
>             }

and

>             location ~ \.php$ {
>             root           html;
>             fastcgi_pass   127.0.0.1:9000;
>             fastcgi_index  index.php;
>             fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
>             include        fastcgi_params;
>             }

with the following which is combined:

> 	       location / {
>             root   html;
>             index index.php index.html index.htm;
>             location ~ \.php$ {
>             root           html;
>             fastcgi_pass   127.0.0.1:9000;
>             fastcgi_index  index.php;
>             fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
>             include        fastcgi_params;
>             }
>             }

thus applying NGINX's PHP only to the root.

Thanks to the devs / huys in the Discord channel for their assistance and hope this helps someone. 

Thanks again

**Comment by Kununa** [comment]
This should definitly be put in the wiki. People like me who switched to docker will often encounter this problem I think.

**Comment by si0972** [comment]
@Kununa its already there, https://github.com/Monitorr/Monitorr/wiki/04-Guide:--Webserver-Configuration#nginx--docker

**Comment by seanvree** [comment]
@BzowK  is this still an issue for you?

**Comment by seanvree** [comment]
I believe this is resolved, please reopen if not.
