### ISSUE TITLE
Conflict with Caddy's templates directive?

### ISSUE THREAD

**Issue by STaRDoGG** [Monitorr/Monitorr#198]
Using the latest Caddy server and Monitorr as of this post, on Windows 10 x64, I add the 'templates' directive to my Caddyfile, and then Monitorr won't load anymore.

Removing the templates directive allows Monitorr to load again as per usual. I've also tried changing the open/close delimiters to no avail.

i.e.
```
templates {
  between (( ))
}
```

I've tried several different delimiters but none seem to allow Monitorr to load. Anyone else have this problem?

**Comment by seanvree** [comment]
@STaRDoGG  I'm vaguely familiar with caddy.  Did you ever figure this out?

Thanks,

**Comment by STaRDoGG** [comment]
@seanvree Unfortunately no. After I posted this I moved onto other TODO's while waiting for a response to this question, but it appears that Monitorr is abandonware.

**Comment by seanvree** [comment]
@STaRDoGG  you're mistaken Sir.  We haven't had to make a lot of changes since it just works - and we've been developing our other project Logarr.  However, development is underway. Please hit us up on Discord and maybe someone knows about Caddy better than I so we can investigate this. Either way, I'm interested. 


https://discord.gg/YKbRXtt

**Comment by STaRDoGG** [comment]
@seanvree ahh sorry, didn't realize you were one of the devs for this app; no offense intended. I'm happy to see there's still interest.

Caddy Server is a very simple, but great web server. Easy to setup and run, etc. It has a MITM (man in the middle) feature that I'm trying to implement in Monitorr, but monitorr seems to not like Caddy's token delimiters that need to be inserted in pages in order to have Caddy recognize them.

https://caddyserver.com/docs/mitm-detection

(Going off memory) in particular it seems that Monitorr doesn't like any of the special characters like parens or braces that need to be wrapped around the tokens.

**Comment by seanvree** [comment]
@STaRDoGG  not need to apologize my freind. 

I'm familiare with what Caddy IS, I just don't know anything about it.  So, I'll ask around and see if anyone is using it.

**Comment by Ramshackles** [comment]
@STaRDoGG I use Caddyserver and just this morning installed Monitorr so I'm not really proficient in Monitorr but I can get templates and the placeholders working.

Now I'm not really sure what you are trying to use them for or how, maybe you could expand with examples and your caddyfile, templates etc.?

What I did to try was add this to my caddyfile for my monitorr subdomain;
```
templates {
   ext .php
 }

```

Then I added (crude I know) this to Monitorrs index.php;
```
<br/>
{{.Now "Monday, 2 Jan 2006"}}
<br/>
{{if .IsMITM}} mitm true {{end}}
{{if not .IsMITM}} mitm false {{end}}
```

Which upon browsing to monitor gave this result;
![billede](https://user-images.githubusercontent.com/1424207/53883080-50c52180-4018-11e9-8256-472ef1e21e38.png)

**Comment by seanvree** [comment]
@STaRDoGG  closing this issue, if you need more help, feel free to continue the discussion on this thread. Or join our discord channel.

Thank you @Ramshackles  for the assistance my man.

**Comment by seanvree** [comment]
added to wiki :  https://github.com/Monitorr/Monitorr/wiki/04-Guide:--Webserver-Configuration#caddy

**Comment by STaRDoGG** [comment]
Aha! Looks like adding the `ext .php` did the trick. Originally I was including a separate .htm with the mitm code in it, within an iframe of a calling page. I added `ext .php .htm` and going to the Monitorr page attempted to download the Monitorr page as a file; removed the .htm from the directive and just renamed the original .htm file as .php, and all's well.

Still pretty new to Caddy myself, lol, thanks guys!
