### ISSUE TITLE
Can't acces with traefik

### ISSUE THREAD

**Issue by zucram** [Monitorr/Monitorr#201]
## Your environment:

- **Operating system**: Ubuntu/Docker

- **Webserver**:      Traefik

- **PHP Version**:     7.1.17

- **Monitorr Version**:  1.7.6m

## Describe your issue:
I'm trying to install monitorr with docker-compose and traefik. Can access it locally but through mydomain.com/monitorr does not work. 
Here is my docker-compose:
  monitorr:
    image: monitorr/monitorr
    container_name: monitorr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/monitorr/:/app
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 8383:80
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=monitorr"
      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefix: /monitorr;"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

Have also set the url in user preferences to mydomain.com/monitorr

I have read the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/06-Troubleshooting

**Comment by seanvree** [comment]
@zucram  I'm not familiar with Traefik at all. I'll have to ask around and see if anyone else is using it.

**Comment by zucram** [comment]
Ok! Let me know how i can help @seanvree

**Comment by zucram** [comment]
I managed to get it working. I had another "frontend" called /monitor (with only one R) and i changed the name for that. And weirdly enough that fixed it. @seanvree

**Comment by seanvree** [comment]
@zucram  that will get ya every time! Glad you got it working my man.
