### ISSUE TITLE
PHP warning with fsockopen & 8.8.8.8:53

### ISSUE THREAD

**Issue by dlwebmaestro** [Monitorr/Monitorr#202]
## Your environment:

- **Operating system**: Windows NT 10.0 build 17763 (Windows 10) AMD64

- **Webserver**:       NGINX v1.15.9

- **PHP Version**:      7.3.0

- **Monitorr Version**:   1.7.7d

## Describe your issue:

I have read the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/06-Troubleshooting

I have the following error multiple times in my web server's error log:
`2019/03/26 12:12:18 [error] 9320#23836: *699933 FastCGI sent in stderr: "PHP Warning:  fsockopen(): unable to connect to 8.8.8.8:53 (An attempt was made to access a socket in a way forbidden by its access permissions.
) in C:\nginx\www\organizr\html\monitorr\assets\php\functions.php on line 457" while reading response header from upstream, client: 172.68.46.154, server: example.com, request: "GET /monitorr/assets/php/systembadges.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "example.com", referrer: "https://example.com/monitorr/index.min.php"`

**Comment by seanvree** [comment]
@dlwebmaestro  - These warning occur when you have the "Check Type" as "Standard" but Monitorr reverts to Ping Only, it's simply indicating that Monitorr is using PING instead of Standard.  They can be safely ignored, However, if you change the "Check Type" to "Ping Only" you will no longer see these warnings.

**Comment by dlwebmaestro** [comment]
Thank you for your reply!  I was actually able to resolve the error by changing the ping host and port to 1.1.1.1:80
