### ISSUE TITLE
Other docker containers only show as Unresponsive

### ISSUE THREAD

**Issue by lastb0isct** [Monitorr/Monitorr#203]
## Your environment:

- **Operating system**: RHEL 7 -- Docker install

- **Webserver**:       Whatever Docker installs

- **PHP Version**:      Same as above

- **Monitorr Version**:   latest docker monitorr/monitorr image

## Describe your issue:

Opening a ticket due to not being able to connect to my webpages properly.  Ping works, curl works but the use of the checkmanual.php shows the following error:

```
//////////////// check START: /////////////// 

Input URL .......... http://192.168.1.200:8099/
CURL URL ........ http://192.168.1.200:8099/ 
! Abnormal URL detected ! 
(Above message is only a warning, script will attempt to check input URL) 
Ping URL ............. 192.168.1.200:8099 
CURL ................... FAIL 
CURL Response .. HTTP : 0 / 0 / CODE: 95 / 0 
PING ................... SUCCESS 
PING Response ... (0) 
URL status .......... OPEN
HTTP/1.1 200 OK
Connection: close
Date: Wed, 01 May 2019 00:04:13 GMT
Content-Type: text/html; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked
e06
```

**Comment by seanvree** [comment]
thanks @lastb0isct I'll look into it.

**Comment by vinaykapadia** [comment]
I'm having a similar issue, but only one container. The rest of my containers show up fine. My Jackett container, though, shows Unresponsive even though it does work.

**Comment by seanvree** [comment]
@vinaykapadia  by "container" I assume you mean "service"?

Jackett is a known issue.  I would change it to "PING ONLY"

**Comment by vinaykapadia** [comment]
By "container" i mean it's running as a docker container, as are all my other services that do show fine. I'll change to PING ONLY. Thanks!

**Comment by seanvree** [comment]
@lastb0isct are you still having this issue?
