### ISSUE TITLE
Custom CSS keeps generating old code

### ISSUE THREAD

**Issue by spicerackk** [Monitorr/Monitorr#207]
## Your environment:

- **Operating system**: Windows 10P x65 build: 1709

- **Webserver**:       NGINX v. 3.8

- **PHP Version**:      7.2.1 x64 NTS

- **Monitorr Version**:   0.21m  (in the footer of the Monitorr UI)

## Describe your issue: added custom CSS for a clock theme, want to remove it, whenever I remove it, and click submit and refresh the page, the code has come back. Custom.css file does not show the code at all, as far as I am aware, it is empty.

I have read the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/06-Troubleshooting

**Comment by seanvree** [comment]
@spicerackk  You have to refresh your browser cache after making any changes to the CSS:

https://github.com/Monitorr/Monitorr/wiki/03-Monitorr-Settings#2-user-preferences

**Comment by spicerackk** [comment]
@seanvree I have, multiple times, and then tried to open the page in an incognito window, and experience the same issue.

**Comment by spicerackk** [comment]
never mind, it just decided to work. I always hard refresh by default now, but it wasn't working. Thanks for the advice!
