### ISSUE TITLE
FEAT: Get Logo

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#21]
"The monitor lizards are large lizards in the genus Varanus. They are native to Africa, Asia and Oceania, but are now found also in the Americas as an invasive species"

Thinking a lizard with big buggy eyes.  You know, cuz he's watching your shit.  

Kinda like this:
![a651bd74667e110b98fa6c68bedc6441--monitor-lizard-lizards](https://user-images.githubusercontent.com/8906637/30515520-44a03880-9ade-11e7-933a-45ac3cb549d8.jpg)

**Comment by Unimatrix0** [comment]
![monitor](https://user-images.githubusercontent.com/357984/31307210-aa2be784-ab24-11e7-9bc1-35260df9ab08.png)

**Comment by seanvree** [comment]
this is dope. Taken from here:

http://www.monitorpestcontrol.co.uk/
