### ISSUE TITLE
Feature: Display data from apps with readonly API support (Sonarr/Radarr/SABNZBD/Tautulli etc) 

### ISSUE THREAD

**Issue by thestraycat** [Monitorr/Monitorr#211]
A feature i have always enjoyed that the Heimdall project implemented was to have important application information displayed in the tile itself. For example, current download data rate from SABnzBD, or how many films are missing in radarr, or how many streams are actively being played via tautulli. It's an invaluable feature and the only thing making me stay with Heimdall at the moment.

**Comment by 1DontEx1st** [comment]
Came here to say the exact same thing, so +1.

**Comment by seanvree** [comment]
Gents, when we first set out to develop this we never intended to compete with other web apps like Organizr and Heimdall .  We wanted to keep this light-weight and simply monitorr the status of services.  I don't foresee us ever implementing something like this. I really recommend Organizr for this.
