### ISSUE TITLE
No option to set user/pass

### ISSUE THREAD

**Issue by JohnDarkhorse** [Monitorr/Monitorr#216]
## Your environment:

- **Operating system**: Ubuntu 18.04.4 LTS

- **Webserver**:       Server version: Apache/2.4.29 (Ubuntu)

- **PHP Version**:      PHP 7.2.24

- **Monitorr Version**:   Commit e480748  and Master: 1.7.6m

## Describe your issue:

I have read the t-shooting Wiki at: https://github.com/Monitorr/Monitorr/wiki/06-Troubleshooting

Trying to install, directory created, files copied but not given a user/pass submission field.

Have attempted using current software version (git clone) and Master release 1.7.6m, with both Firefox & Chromium browsers without success.

![monitor-install](https://user-images.githubusercontent.com/25340517/75621781-98fd1e00-5b5e-11ea-8d8f-d5ad1c33f7b5.jpg)

**Comment by jonfinley** [comment]
Could you give us some output from the apache logs and browser console?
