### ISSUE TITLE
BUG:  Column / Row Distribution

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#27]
Issue:  Service tiles are not populating in rows and columns properly 

Suggestion: 

Default:  Need to set default display of 6 tiles wide 
Interim:  Possible use tables? 
End result:  Be able to define ROWs for each service via the /assets/config file.

**Comment by seanvree** [comment]
@wjbeckett  - 

Have you worked on this at all brother?  

Let's go ahead and push what we got now.  If we have to put them all one ONE row, fine...but I'd like to have something out there other than just stuck with 4 columns on the top row.  LMK

**Comment by wjbeckett** [comment]
Fixed layout and overflows in https://github.com/Monitorr/Monitorr/commit/599aa709bf5be11d56d8ed566bc4a115cf3d3781
