### ISSUE TITLE
FEAT: 12HR Clock Format

### ISSUE THREAD

**Issue by jrdnlc** [Monitorr/Monitorr#38]
Just like the title states. Would like to have an option to choose between 12/24hr clock in the `assets/config.php` file and option to remove `seconds` and be able to use `am/pm`

**Comment by seanvree** [comment]
@jrdnlc  got it.  Thanks for the feedback. I'll look into this.

**Comment by jonfinley** [comment]
will Add ability to switch in settings php #24

**Comment by jonfinley** [comment]
done: https://github.com/Monitorr/Monitorr/commit/54e8adb77a03367edadc52816c823099ecc8e519

**Comment by jrdnlc** [comment]
That was fast. Thank you! @jonfinley

**Comment by jonfinley** [comment]
No Problem @jrdnlc!! Really pushing towards quite a few updates!

**Comment by jonfinley** [comment]
Not following config file. back under review

**Comment by jonfinley** [comment]
Merged #56
