### ISSUE TITLE
Rewrite Index and Functions files

### ISSUE THREAD

**Issue by wjbeckett** [Monitorr/Monitorr#47]
Layout issues with Bootstrap are  making me want to rewrite it from scratch.
Putting this in for v1 as it'll require a considerable amount of work as the functions file needs to be rewritten/condensed too.

**Comment by wjbeckett** [comment]
this will also include a rewrite of the bootstrap CSS to bring it up to bootstrap 4.

**Comment by seanvree** [comment]
Not needed.
