### ISSUE TITLE
Can't use bg gradient and can't change button radius

### ISSUE THREAD

**Issue by veganexe** [Monitorr/Monitorr#52]
If I use bg gradient in the body section of main.css, I get a page with background tiling vertically into 3 rows. A single background color works properly with no tiling.

And no matter what radius I use for btnonline and btnoffline, I can't change the shape of the buttons.

**Comment by wjbeckett** [comment]
@veganexe, can you share the code your using to add the gradient?

**Comment by veganexe** [comment]
Never mind. Mistake on my end. Closing issue
