### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by binaryronin** [Monitorr/Monitorr#57]
I created a Docker image for the project. It's a little tweaky because of needing to edit the config, but it works. It would be better if we could populate the config via environment variables or just use the UI to edit the settings, but again, it works.

It can be found here: https://github.com/binaryronin/monitorr-docker

**Comment by wjbeckett** [comment]
awesome! thanks for putting this together.

Our goal is to have the configuration managed from the UI. We're definitely working towards that so the config.php editing won't be around forever.

**Comment by binaryronin** [comment]
Awesome! I figured as much! Once that is in place I can edit the build to no longer need the external `config.php`.

If there is something in the container that you see that you would like differently please let me know.

**Comment by wjbeckett** [comment]
No problem.
Are you on Gitter? You should jump into the gitter channel so we can keep
in touch.

Join the chat: https://gitter.im/Monitorr/Chat

Talk to you in Gitter.

**Comment by seanvree** [comment]
Created branch https://github.com/Monitorr/Monitorr/tree/docker .

Also created Dockerhub repo here:  https://hub.docker.com/r/monitorr/monitorr/

Dockerhub is on an automated build, so anytime we update the docker branch, should update the dockerhub repo. 

Someone check my work. LOL.
