### ISSUE TITLE
Gogs

### ISSUE THREAD

**Issue by Doonut** [Monitorr/Monitorr#59]
My gogs server is always showing offline

**Comment by wjbeckett** [comment]
Need a bit more info.
What does the URL look like that your are trying to monitor (remove any sensitive info)?

Can you `curl` they URL you are trying to monitor?

**Comment by Doonut** [comment]
Ive been trying with http://localhost:3000 and a reverse proxy address http://git.domain.com, the reverse proxy and/or localhost work for all other services

**Comment by wjbeckett** [comment]
can you `curl http://localhost:3000` ?

**Comment by Doonut** [comment]
http://termbin.com/pe2w

**Comment by wjbeckett** [comment]
can you run this one:
`curl -X HEAD -I http://localhost:3000`

What is the http response?

**Comment by Doonut** [comment]
404 Not Found
http://termbin.com/5emuz

**Comment by wjbeckett** [comment]
come jump in here
https://gitter.im/Monitorr/Chat?utm_source=share-link&utm_medium=link&utm_campaign=share-link

that way we don't flood the issue.

**Comment by Doonut** [comment]
use http://gogs.domain.com/healthcheck
