### ISSUE TITLE
FEAT:  Add Disable Auto-refresh

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#80]
**Feature addition:**   small toggle switch to disable auto-refresh. 
**Code Reference:**    https://codemyui.com/toggle-switch-collection-using-pure-css-custom-properties/
**Status**:                 TESTING

**STATUS**:

- [x] (OK) Functionality
- [x] (OK) UI Desktop browsers:  Looks dope. 
- [x] (OK) UI Android:  Looks dope 
- [x] (OK) UI iOS: looks dope. _FIXED: Displays switch on top of TITLE. Need to figure out how to AUTO-adjust title to smaller font size on smaller screens so there is no overlap._ 
- [x] (Pending) Pushed to DEV
- [x] (Pending) Merged with master
- [x] (Pending) Wiki updated
- [x] (Pending) Release published

Wiki changes for Org plug in need to change to this:

```
    <div style="overflow:hidden; height:270px">    
        <embed style="height:100%" width='100%' src='https://yourdomain.com/monitorr/index.min.php' />
    </div>
```

![image](https://user-images.githubusercontent.com/8906637/34473196-68c9a576-ef24-11e7-8478-b041d2f7ae17.png)

**Comment by seanvree** [comment]
https://codepen.io/JosephShenton/pen/YqVoJB

**Comment by seanvree** [comment]
added to Alpha branch:

https://github.com/Monitorr/Monitorr/commit/1b9f2b9d3db69b4342e3d99ecdf7f427e2fc2e76

**Comment by seanvree** [comment]
@causefx  you have any idea how to do this?

**Comment by causefx** [comment]
You want to just have the size smaller on small screens?

**Comment by seanvree** [comment]
@causefx yeah, need to adjust the title text size somehow. All the cells adjust fine with the browser, but need to adjust the size of the font in the CENTER div only once it get's to a really small horizontal size. Would that be a bootstrap thing?

see here:  https://seanvree.com/dev/monitorralpha

HTML:
```
        <div class="header">

            <div id="left" class="Column">
            </div>

            <div id="center" class="navbar-brand">
            </div>

            <div id="right" class="Column">
            </div>

        </div>
```

CSS:

```
.Column {
    display: table-cell;
}

table,
th,
td {
    padding-left: 5px;
    padding-right: 5px;
}


#left {
    text-align: left;
    vertical-align: middle;
    width: 30%;
    z-index: -1;
}

#center {
    text-align: center;
    vertical-align: middle;
    /* width: 100%; */
    float: right;
    /* margin-left: 21%; */
}

#right {
    text-align: center;
    vertical-align: middle;
    width: 30%;
    cursor: default;
    font-size: .8em;
}
```

**Comment by causefx** [comment]
Yeah u just need to use media and screen size. When I’m at computer I’ll write it

**Comment by seanvree** [comment]
@causefx thanks brotha!

I already have @media values. 

Just saw maybe I can use "Font-size: 5vw" instead of 5px?  Anything wrong with that?

**Comment by seanvree** [comment]
@causefx  Got it.  Thanks for the tip. REM!!!!


![image](https://user-images.githubusercontent.com/8906637/34407574-ea9c6c00-eb73-11e7-87e0-8c33bc43bf2b.png)

**Comment by seanvree** [comment]
Complete:  https://github.com/Monitorr/Monitorr/releases/tag/v0.12.0m
