### ISSUE TITLE
FEAT: Remove URL from icons option

### ISSUE THREAD

**Issue by 1activegeek** [Monitorr/Monitorr#88]
## Your environment:

- **Operating system**: Docker Container (Official)

- **Monitorr Branch**:   Master

## Describe your issue:

The goal would be to allow the user to REMOVE the hyperlink behind certain icons or even all icons. Specifically, I display this at the top of a screen in Organizr. When a user logs in, I show them Plex, Requests, NZBget, Sonarr, Radarr statuses. The goal is to show that all systems are up and available or if not, that there is an issue obviously. I'd like to remove the links though for NZBget/Radarr/Sonarr - because they won't have access and I don't want them to click on it and think something is broken.

**Comment by 1activegeek** [comment]
@jonfinley

**Comment by wjbeckett** [comment]
If you leave the url part of the config blank it'll do what you want and
not link to anything.

**Comment by seanvree** [comment]
@1activegeek  this is a good point. When we initially were deving we explored the possibility of putting in a custom link when a service is down to say uptime robot...so right now, it should redirect you back to your monitorr page if its down.  Which it is doing.  So that's what we put in place.  Is that working for you?  Or you're just concerned about it actually being a clickable link eventho it's down?  So a way to completely disable the clickable link if its' down?

**Comment by 1activegeek** [comment]
@wjbeckett - I'm not sure I understand you. If I don't put in a link, how does it know what to ping for being up? 

@seanvree - my concern is even when it's up - if user logs in and see's those 5 icons, like my buddy did, they go to click on it and it opens a new tab and says you're not authorized. I'd like to just remove any clickable link on 3/5 icons.

**Comment by 1activegeek** [comment]
![screen shot 2018-01-04 at 12 40 50 pm](https://user-images.githubusercontent.com/6810720/34576627-89cd90d2-f14c-11e7-8058-5ad896e03ed8.png)
So I just want Plex/Requests to be able to open the appropriate app, but Downloader/TV/Movies to be just an image to show up/down status

**Comment by seanvree** [comment]
@1activegeek  Okay, I see. so essentially if it's down...disable the link completely for the down service..and only for that service.  We'll explore this. 

Thanks!

**Comment by 1activegeek** [comment]
@seanvree Close! I don't want a link available at all - whether it's up or down. I just want the icon to show, the title to show, and the online/offline to show. No ability to click the icon/title and open the linked app. In the screenshot above, this is the view for a User logging in, but the apps behind those icons are not available to User level permission - on purpose.

I'd just like to inform them that those services are running or not. The idea is, if something is wrong with NZBget, I'd like to them to realize hey the downloader isn't working right now, so when you put in your request, it may not really download anytime soon. Or if you're sitting around waiting for the latest episode, but the Sonarr app isn't working - you won't be getting as soon as it becomes available.

**Comment by seanvree** [comment]
@1activegeek  Ohhhhhkaay.  SO you're talking a manual config thing then...obvi this couldn't be done automatically.  got it.

**Comment by 1activegeek** [comment]
Correct - ya just want to be able to select on my own and say that one, link doesn't work. The rest of how it functions when apps go down and such is fine.

**Comment by seanvree** [comment]
got it.

**Comment by seanvree** [comment]
Added change to DEVELOP for testing. 

- changed offline service link behavior. See https://github.com/Monitorr/Monitorr/issues/88
a.  OFFLINE service tile link will now be disabled EXCEPT for the service title which the cursor will show "not-allowed". The decision to make the service title still "clickable" is in the case of a webserver misconfig in which the service UI might still be UP but Monitorr is reporting it as down.

**Comment by 1activegeek** [comment]
@seanvree - is there a way I can build the docker contianer to test? I think we just discovered recently in Discord that the docker build is separate since the recent push didn't update the container build at all. I only run in container, so that would be my platform to test.

**Comment by seanvree** [comment]
@1activegeek unfortunately not. The DH build is automated from the GH master branch.  Should be pushed in a few hours. 

However, you can take a look at it from my rig:

https://tinyurl.com/ybxx66b5

P.S. this update will fix the DH branch updating automatically when we update the master branch on GH. 

Thanks for your help brotha.

**Comment by seanvree** [comment]
@1activegeek  Complete brotha. LMK what you think. 

Pushed to master AND dockerhub. 

https://github.com/Monitorr/Monitorr/releases/tag/v0.12.4m

https://hub.docker.com/r/monitorr/monitorr/builds/

**Comment by 1activegeek** [comment]
Maybe I missed something ... how would I now remove the link from a particular item being monitored? Just to refresh, the ask is to remove a link completely, regardless of status. I think the update you have was mostly around up/down link activation.

**Comment by seanvree** [comment]
@1activegeek  Yeah, you are missing something.  BLUF:  It's not possible.  You can't remove the "link" from the UI as the link is how the app determines if it's up or down.  What you're talking about is providing "alternate" target links, separate from the target "moniotrring" link.  This will be added in a few weeks when we add the dedicated settings page.  This is a work-around for now.

**Comment by 1activegeek** [comment]
Ahhh ok, I'll keep my eyes peeled for that one.
