### ISSUE TITLE
Docker branch dont get updates

### ISSUE THREAD

**Issue by si0972** [Monitorr/Monitorr#91]
Docker braanch is stuck on the version it got forked from. When you use the inbuilt updater it works until you rebuild the docker. (think of it like a snapshot)

Proposed change: add the dockerfile to each branch. OR update docker branch whem master gets updates.

**Comment by seanvree** [comment]
@si0972  roger that brotha.  Forgot that.

**Comment by seanvree** [comment]
Fixed.  DockerHub Repo is now auto-updated when GH docker branch is updated which is also auto-updated when GH master branch is updated.
